export const MQTT_SET_PAYLOAD = "MQTT_SET_PAYLOAD";
export const MQTT_SET_IS_SUBBED = "MQTT_SET_IS_SUBBED";
export const MQTT_SET_CONNECT_STATUS = "MQTT_SET_CONNECT_STATUS";
export const MQTT_SET_CLIENT = "MQTT_SET_CLIENT";

export const APP_SET_INSTALL_STATUS = "APP_SET_INSTALL_STATUS";
